name: Test Install & Uninstall Scripts

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'install.sh'
      - 'uninstall.sh'
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'install.sh'
      - 'uninstall.sh'
      - 'tests/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Run bats tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bats (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Install bats (macOS)
        if: matrix.os == 'macos-13'
        run: |
          brew install bats-core

      - name: Make scripts executable
        run: |
          chmod +x install.sh
          chmod +x uninstall.sh

      - name: Run install tests
        run: bats tests/install.bats

      - name: Run uninstall tests
        run: bats tests/uninstall.bats

      - name: Test summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ All tests passed for ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
